server:
  port: 11451
spring:
  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 60MB
  datasource:
    url: jdbc:mysql://localhost:3306/pan_db?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    cn.itcast: debug
  pattern:
    dataformat: MM-dd HH:mm:ss:SSS